//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MIM.rc
//
#define SERVER                          0
#define UL                              0
#define CLIENT                          1
#define DL                              1
#define IDC_REFRESH                     3
#define IDC_ADD                         4
#define IDC_UPDATE                      5
#define IDC_VIEW                        6
#define IDC_SYNC                        7
#define IDSAVEAS                        8
#define IDM_ABOUTBOX                    0x0010
#define ID_MAX                          20
#define IDD_ABOUTBOX                    100
#define PACKETGAP                       100
#define IDS_ABOUTBOX                    101
#define IDD_MIM_DIALOG                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define FILEINF                         109
#define FILEDONE                        110
#define STOP                            111
#define OK                              112
#define SFILE                           113
#define ID_PING_TIMER                   114
#define ID_FLOOD_TIMER                  115
#define IDR_RICHTEXTBAR                 116
#define MESG                            116
#define REG                             117
#define VOTE                            118
#define ULIST                           119
#define PROF                            120
#define PING                            121
#define ME                              122
#define MBOX                            123
#define AWAY                            124
#define SHOWICON                        126
#define RIP                             127
#define IDR_MAINFRAME                   128
#define SIP                             128
#define IDR_TEXTBAR                     129
#define PAUSE                           129
#define FREG                            130
#define RWAITING                        131
#define IDB_SETTINGS                    133
#define WHISPER                         133
#define IDB_CONNECT                     134
#define USER                            134
#define IDB_DISCONNECT                  135
#define ID_STATUSBAR                    135
#define IDB_CMESS                       136
#define IDB_SMESS                       137
#define IDR_MIM                         138
#define IDB_SENDFILE                    139
#define IDB_VIEWPROFILE                 140
#define STYPE                           140
#define IDB_IGNORE                      141
#define ETYPE                           141
#define IDI_ADMIN                       142
#define ID_TYPE_TIMER                   142
#define IDI_ICON7                       142
#define IDI_AWAY                        143
#define MOD                             143
#define IDI_NET                         144
#define RNAME                           144
#define IDI_EXCLAM                      145
#define DLNEWO                          145
#define IDI_IP                          147
#define IDI_MUTE                        149
#define DLNEW                           149
#define IDI_PASSWORD                    150
#define ROLL                            152
#define IDI_USER                        153
#define INFO                            153
#define IDI_YOU                         154
#define REQINFO                         154
#define IDR_MAINMENU                    155
#define IDI_ICON1                       155
#define IDB_SERVEROP                    156
#define IDR_USERMENU                    156
#define IDI_ICON0                       156
#define CLIPBOARD                       156
#define IDR_ICONMENU                    157
#define IDI_ICON3                       157
#define PSL                             157
#define IDD_PASSWORD                    158
#define IDI_ICON4                       158
#define MSL                             158
#define IDD_HELP                        159
#define IDI_ICON5                       159
#define IDB_EDITPROFILE                 160
#define IDI_ICON2                       160
#define IDD_PROFILE                     161
#define IDB_64                          162
#define IDI_ICON6                       162
#define IDD_SERVER                      163
#define IDI_RED                         163
#define IDI_GREEN                       164
#define IDD_SETTINGS                    165
#define IDB_CLIENT                      166
#define IDD_AGREE                       166
#define IDB_SERVER                      167
#define IDD_MBOX                        167
#define IDB_LOGO                        169
#define IDB_LISTEN                      170
#define IDD_SENDFILE                    171
#define IDB_SEND                        173
#define IDB_PREV                        174
#define IDB_TRAY                        176
#define IDR_SHOWMENU                    178
#define IDR_INPUTMENU                   179
#define IDB_KICK                        179
#define IDB_MBOX                        180
#define IDB_SIMPLE                      181
#define IDB_DETAILS                     182
#define IDD_SAVEDL                      185
#define IDR_ACCELERATOR1                186
#define IDD_INTRO                       186
#define IDD_PUBPAD                      187
#define IDC_PENCIL                      192
#define IDB_BG                          193
#define IDC_LINE                        193
#define IDC_ERASER                      194
#define IDB_PUBPAD                      194
#define IDD_MASTERLIST                  194
#define IDD_ADDSERVER                   195
#define IDD_TOOLBOX                     196
#define IDC_ROOM                        1000
#define IDC_TYPE0                       1000
#define IDC_SEND                        1001
#define IDC_TYPE1                       1001
#define IDC_MESSAGE                     1002
#define IDC_SCREENNAME                  1002
#define IDC_USERLIST                    1003
#define IDC_PORT                        1003
#define IDC_TIMEOUT                     1004
#define IDC_ADDNEW                      1005
#define IDC_REMOVE                      1007
#define IDC_SETTINGS                    1008
#define IDC_REMOVEALL                   1008
#define IDC_CONNECT                     1009
#define IDC_DISCONNECT                  1010
#define IDC_CLEAR                       1011
#define IDC_BITSERVER                   1011
#define IDC_SAVEMESS                    1012
#define IDC_BITCLIENT                   1012
#define IDC_ROOMNAME                    1013
#define IDC_IGNORE                      1014
#define IDC_VIEWPROFILE                 1015
#define IDC_SENDFILE                    1016
#define IDC_USERS                       1017
#define IDC_PREV                        1018
#define IDC_OPTIONS                     1019
#define IDC_PASS                        1019
#define IDC_EDITPROFILE                 1020
#define IDC_LIVE                        1020
#define IDC_ADMINNAME                   1020
#define IDC_PETS                        1021
#define IDC_KICK                        1021
#define IDC_EMAIL                       1022
#define IDC_MBOX                        1022
#define IDC_AGE                         1023
#define IDC_OTHER                       1023
#define IDC_GENDER                      1024
#define MAX                             1024
#define IDC_PUBPAD                      1024
#define IDC_GENDER2                     1025
#define IDC_QUOTE                       1026
#define IDC_ANIMATE                     1027
#define IDC_NAME                        1028
#define IDC_MAX                         1029
#define IDC_SPORT                       1030
#define IDC_LISTENPORT                  1030
#define IDC_PASSWORD                    1031
#define IDC_ASK                         1032
#define IDC_CENSOR                      1033
#define IDC_IPCOMBO                     1034
#define IDC_SMAX                        1034
#define IDC_COMPNAME                    1035
#define IDC_YOURIP                      1036
#define IDC_VERSION                     1037
#define IDC_BANNED                      1037
#define IDC_TEXT                        1038
#define IDC_MODPASS                     1038
#define IDC_BIT                         1039
#define IDC_BOUNCER                     1039
#define IDC_INFO                        1040
#define IDC_BSECONDS                    1040
#define IDC_EULA                        1041
#define IDC_MINICON                     1042
#define IDC_SOUND                       1046
#define IDC_SBROWSE                     1047
#define IDC_SOUNDDIR                    1048
#define IDC_ANI                         1049
#define IDC_ABROWSE                     1050
#define IDC_ANIDIR                      1051
#define IDC_TRAY                        1051
#define IDC_ALLOWRUN                    1052
#define IDC_SIMPLE                      1052
#define IDC_BROWSER                     1053
#define IDC_BBROWSE                     1054
#define IDC_AUTOSAVEMESS                1055
#define IDC_LISTENABLE                  1056
#define IDC_AUTOLOGIN                   1057
#define IDC_OPENTEXT                    1059
#define IDC_TIMESTAMP                   1060
#define IDC_MESS                        1061
#define IDC_PUBLIC                      1061
#define IDC_DATE                        1063
#define IDC_PROGRESS1                   1064
#define IDC_PROGRESS2                   1065
#define IDC_SPEED                       1066
#define IDC_FILE                        1071
#define IDC_AUTO1                       1071
#define IDC_FILE2                       1072
#define IDC_AUTO2                       1072
#define IDC_FILENAME                    1073
#define IDC_IPLIST                      1073
#define IDC_ANIMATION                   1074
#define IDC_IP                          1074
#define IDC_CONNECTION                  1075
#define IDC_COMMENT                     1075
#define IDC_OTHERNAME                   1076
#define IDC_IDLE                        1077
#define IDC_COPYRIGHT                   1079
#define IDC_RFRAME                      1085
#define IDC_THICKNESS                   1089
#define IDC_COLOR                       1090
#define IDC_TOOL                        1091
#define IDC_TOOL2                       1092
#define IDC_BSTATIC                     1092
#define IDC_TOOL3                       1093
#define IDC_BSTATIC2                    1093
#define IDC_UNDO                        1094
#define IDC_USERNAME                    1094
#define IDC_REDO                        1095
#define IDC_TOOLWIN                     1096
#define IDC_BUTTON1                     1097
#define IDC_TESTBUT                     1098
#define IDC_MLIST                       1099
#define IDC_STOP                        1101
#define PACKETMAX                       4000
#define IDC_FONTNAME                    32771
#define IDC_FONTSIZE                    32772
#define IDC_CHAR_BOLD                   32773
#define IDS_CONSETTINGS                 32773
#define IDC_CHAR_ITALIC                 32774
#define IDS_SERVEROPTIONS               32774
#define IDC_CHAR_UNDERLINE              32775
#define IDC_CHAR_STRIKEOUT              32776
#define IDC_CHAR_COLOR                  32777
#define ID_FILE_EXIT                    32781
#define ID_FILE_LOADSETTINGS            32782
#define ID_FILE_SAVESETTINGS            32783
#define ID_FILE_SAVEMESSAGES            32784
#define ID_NETWORK_CONNECTIONSETTINGS   32785
#define ID_NETWORK_SERVEROPTIONS        32786
#define ID_FILE_RESTORESETTINGS         32787
#define ID_HELP_README                  32788
#define ID_HELP_PATCH                   32789
#define ID_HELP_HELP                    32790
#define ID_HELP_ABOUT                   32791
#define ID_HELP_EULA                    32792
#define ID_USER_SENDFILE                32793
#define ID_USER_IGNORE                  32794
#define ID_USER_VIEWPROFILE             32795
#define ID_USER_KICK                    32796
#define ID_USER_MYSTATUS_DISCONNECT     32797
#define ID_USER_MESSAGE                 32798
#define ID_ICON_RESTORE                 32799
#define ID_ICON_EXIT                    32800
#define ID_USER_STATUS_AVAILABLE        32801
#define ID_USER_STATUS_AWAY             32802
#define ID_ICON_STATUS_AVAILABLE        32803
#define ID_ICON_STATUS_AWAY             32804
#define ID_ICON_STATUS_CONNECT          32805
#define ID_ICON_STATUS_DISCONNECT       32806
#define ID_SHOWMENU_FOLLOWURL           32808
#define ID_SHOWMENU_COPY                32809
#define ID_INPUTMENU_CUT                32810
#define ID_INPUTMENU_PASTE              32811
#define ID_INPUTMENU_SELECTALL          32812
#define ID_INPUTMENU_COPY               32813
#define ID_INPUTMENU_UNDO               32814
#define ID_NETWORK_SERVERTEXT           32815
#define ID_USER_BAN                     32816
#define IDC_CHAR_BACK                   32817
#define ID_GOOGLE                       32818
#define ID_DICTIONARY                   32819
#define ID_SHOWMENU_FIND                32820
#define ID_CTRL_F                       32821
#define ID_FILE_VIEWHISTORY             32823
#define ID_FILE_VIEWQUOTES              32824
#define ID_FILE_VIEWCOMMANDS            32825
#define ID_FILE_LOADCOMMANDS            32826
#define ID_FILE_OPENDOWNLOADFOLDER      32827
#define ID_FILE_LOADSERVERTXT           32828
#define ID_FILE_VIEW_SERVERTXT          32829
#define ID_FILE_LOADBOUNCER             32831
#define ID_FILE_OPENBOUNCER             32832
#define ID_NETWORK_MASTERSERVER         32833
#define ID_FILE_SAVE32834               32834
#define ID_LOAD_MASTER                  32835
#define ID_SAVE_MASTER                  32836
#define ID_USER_SENDCLIPBOARD           32837
#define ID_USER_READCLIPBOARDFROMFILE   32838
#define ID_OPEN_CLIPBOARD               32839
#define ID_SAVE_CLIPBOARD               32840
#define ID_LOAD_CLIPBOARD               32841
#define ID_SAVE_CLIPBOARD_QUICK         32842
#define ID_SAVE_MSL                     32843
#define ID_LOAD_MSL                     32844

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32845
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           159
#endif
#endif
